### ISSUE TITLE
HTML Editor Manager does not load on large multilingual site

### ISSUE THREAD

**Issue by puresystems** [DNN-Connect/CKEditorProvider#80] opened 2017-06-21 12:14 UTC
Hi,

Using DNN Platform 08.00.04 (226) the HTML Editor Manager page won't load and seems to cause the site to timeout until we recycle the App pool. 

The site has around 300 pages, but has been localised to 9 other languages with similar number of pages. So 1 portal but 10 locales using the DNN localisation.

Monitoring the server resources whilst this is happening, we can see the SQL server CPU rises to around 50%. Is there an issue with it loading the pages possibly?

**Comment by Xand0r** [comment] 2017-07-26 13:43
I've experienced a similar issue where, after selecting the CKEditor in the dropdown on the HTML Editor Manager page, it seems to load indefinitely.  After several attempts to load it, it suddenly works, but I haven't determined exactly how or why it starts working.

**Comment by sleupold** [comment] 2017-07-26 14:10
I doubt that this issue is caused by the editor provider, but would you mind to use the SQL Server Profiler to identify the SQL Statement causing the issue, thanks.

**Comment by puresystems** [comment] 2017-11-13 12:23
We've finally got around to looking into this again and so have setup a DNN v9.1.1 staging site with the same data.

Using SQL Profiler, when we try to load the HTML Editor Manager we see this entry about every second:

exec sp_executesql N';Exec dbo.GetModuleSettings @0',N'@0 int',@0=18306

the ID is different each time though.

**Comment by sleupold** [comment] 2017-11-13 12:29
dbo.GetModuleSettings is a DNN core procedure, but usually, settings should be cached.
What is the cache level settings in your Server > Performance section?
Please disable Scheduler to make sure, the calls are not caused by Search indexing background thread.

**Comment by puresystems** [comment] 2017-11-13 15:10
Caching is set to Heavy and nothing else is running - the SQL is definitely in response to trying to load the HTML Editor Manager. There are about 100 / second (not 1 / second as previously stated).

**Comment by sleupold** [comment] 2017-11-13 15:18
this sounds definitely like a bug.

**Comment by sleupold** [comment] 2017-11-13 15:19
please log the issue as well on http://support.dnnsoftware.com and link to this issue.

**Comment by valadas** [comment] 2020-09-18 19:57
This issue is quite old and had no comments for almost 3 years. In that time there was a lot of platform improvements for performance. If this is still a reproducible in Dnn 9.7.1 please open a new issue at https://github.com/dnnsoftware/Dnn.Platform as we are moving this project to the main repository with https://github.com/dnnsoftware/Dnn.Platform/pull/4096

**Closed as completed by valadas** 2020-09-18 19:57 UTC
