### ISSUE TITLE
Styles for textbox spinners

### ISSUE THREAD

**Issue by jbrinkman** [DNN-Connect/CKEditorProvider#3] opened 2015-05-12 23:06 UTC
The styles for the textbox spinners in the Editor Options are not correct.  The spinner icons should be vertically aligned.  Also, the tooltip does not display correctly when using the spinner.

**Comment by ohine** [comment] 2015-06-29 18:25
It looks like the original provider was updated to use the dnn styled loading screen. I'll pull those updates next.

**Comment by valadas** [comment] 2020-09-18 18:24
I am assuming this is now resolved with the commit mentioning this issue, if I am wrong, we are merging this project into the Platform repository with https://github.com/dnnsoftware/Dnn.Platform/pull/4096, so please open a new issue there with where to see this (steps to reproduce). Thanks

**Closed by valadas** 2020-09-18 18:24 UTC
