### ISSUE TITLE
error when linking to a portal file when the foldername contains an apostrof (')

### ISSUE THREAD

**Issue by mstokericatt** [DNN-Connect/CKEditorProvider#138] opened 2019-12-31 10:58 UTC
steps to reproduce:
1 in the editor add a link
2 select linktype 'portalfile or other URL'
3 click 'browse on the server '
4 select a file inside a folder with an apostrof in the name (for example ../pfd's/)
5 click 'ok' 
result : white screen
javascript error: missing ) after argument list
this line causes the error, because the quote in the foldername is not escaped:
E.CKEDITOR.tools.callFunction(1,'/Portals/xxx/PDF's/yyy.pdf?ver=2019-09-27-155548-553','')

**Comment by valadas** [comment] 2020-09-18 22:03
I cannot reproduce this issue in dnn 9.7.1
We are moving this project to the main Platform repository at https://github.com/dnnsoftware/Dnn.Platform so if this is still valid, please open a new issue there. Thanks.

**Closed as completed by valadas** 2020-09-18 22:03 UTC
