### ISSUE TITLE
Replacing image does not replace the image

### ISSUE THREAD

**Issue by Tychodewaard** [DNN-Connect/CKEditorProvider#140] opened 2020-03-16 16:47 UTC
If you use the CKeditior in an html module and upload an image, while 'replace image' is flagged, the image is nog replaced but a new one created with _1 to identify it's new.

**Comment by valadas** [comment] 2020-09-18 22:06
I think this is by design to prevent replacing an image in the filesystem that may be linked anywhere else on the site.
We are moving this project to https://github.com/dnnsoftware/Dnn.Platform and if I am wrong and a change of behavior is needed, please open a new discussion there to see if we have an agreement in doing such change before we make it an issue. Thanks.

**Closed as completed by valadas** 2020-09-18 22:06 UTC
