### ISSUE TITLE
Editor re-writes HTML when startup mode is set to wysiwyg

### ISSUE THREAD

**Issue by muddeatr** [DNN-Connect/CKEditorProvider#102] opened 2019-02-13 14:21 UTC
If the editor Startup Mode is "wysiwyg" and I switch to Source mode when opening a dnn module for edit the source html is re-written by the editor if it believes the source is not compliant. This breaks a lot of special effects that we have with gallery overlays and such.

If the Startup Mode is "source" and I open the module for edit the source html is fine as long as I don't toggle the source button.

**Comment by ghost** [comment] 2019-10-24 18:31
Request for follow up on this issue. I'm evaluating the health of this repository and would like to know if this was ever resolved or if this dependency just doesn't care about issues.

**Comment by muddeatr** [comment] 2019-10-24 18:48
As far as I know it is still an issue. I have uninstalled the editor because of the issues and reverted back to the old editor. I would like to be kept up on the update so I can re-install it and try it again.

**Comment by muddeatr** [comment] 2019-10-24 18:52
Just a thought here @etisdew . Maybe you can add a toggle setting for advanced user to turn off strict HTML enforcement and allow the user to make their own mistakes if they use this setting.

**Comment by Timo-Breumelhof** [comment] 2019-10-24 20:27
This DNN CkEditor is like a wrapper around the existing CkEditor.
Actually that behavior is by design. It's a CkEditor" feature, not really an issue of this project.
You can however reconfigure the way the editor behaves.
You can read how here: https://github.com/DNN-Connect/CKEditorProvider/issues/129

**Comment by Timo-Breumelhof** [comment] 2019-10-25 11:33
Ok, as this question has come up a few times lately, I wrote a blog post about it: https://dnncommunity.org/blogs/Post/2841

**Comment by muddeatr** [comment] 2019-10-25 13:26
But this question is STILL legit. For me anyways the editor re-writes my HTML according to it's "rules".
Here's a block of my HTML
![image](https://user-images.githubusercontent.com/17751004/67575145-ea595480-f709-11e9-9a58-903ff9662d71.png)
And here is what happens to that HTML when I open it using the editor. Note the changes in the way the HTML and this was done just by opening the existing HTML code. If I didn't notice and saved then my HTML wouldn't work the way it was intended by me to work not an HTML editor.

Here's the CkEditor:
![image](https://user-images.githubusercontent.com/17751004/67575186-04933280-f70a-11e9-9796-effb0de7134d.png)

**Comment by muddeatr** [comment] 2019-10-25 13:31
Oh and that was after I added the "extraAllowedContent" from your blog.

**Comment by Timo-Breumelhof** [comment] 2019-10-25 13:41
Could you try this without the 

`<center>` as that is  not supported in HTML5 https://www.w3schools.com/tags/tag_center.asp

**Comment by Timo-Breumelhof** [comment] 2019-10-25 13:43
Off topic, but if you are inserting such specific HTML, please consider researching a structured content module like Open Content. That is much more controllable and scalable.

**Comment by muddeatr** [comment] 2019-10-25 13:53
It's not the center tag. It's the fact that the editor is trying to enforce a "div" tag is not allowed between the opening and closing "a" anchor tags so it moves the. Here's without the center tag. And with Bootstrap and/or Bootstrap variants using div's with just a span in it to display their icons, this editor reconfigures that as well. And don't get me wrong, I wish I can get this working because I love the CKEditor UI much better.

My HTML
![image](https://user-images.githubusercontent.com/17751004/67576719-132f1900-f70d-11e9-9762-32d759a7b9c7.png)

CKEditor
![image](https://user-images.githubusercontent.com/17751004/67576775-2f32ba80-f70d-11e9-89e0-c22ee8ccc706.png)

**Comment by Timo-Breumelhof** [comment] 2019-10-25 14:02
Ah, right. Seems like an issue for others too: https://dev.ckeditor.com/ticket/9457 might have been fixed in CK 5?

**Comment by w8tcha** [comment] 2019-10-25 14:04
This happens because CKEditor 4 only supports HTML 4 dtd. Html5 is not supported. However there is a workaround

https://github.com/ckeditor/ckeditor4/issues/514

You would need to place the js code in your site. For example via the custom js option in the editor provider.

**Comment by muddeatr** [comment] 2019-10-25 14:15
So then is any of this available for DNN?

**Comment by OllyHodgson** [comment] 2019-10-25 21:26
@muddeatr

> So then is any of this available for DNN?

As @w8tcha said:

> You would need to place the js code in your site. For example via the custom js option in the editor provider.

If I remember correctly (I don't have a DNN install in front of me right now), I _think_ you can visit Site Settings > Site Behavior > More > HTML Editor Manager, find the Custom JS box, and paste in:

```javascript
CKEDITOR.dtd['a']['div'] = 1;
CKEDITOR.dtd['a']['p'] = 1;
CKEDITOR.dtd['a']['i'] = 1;
CKEDITOR.dtd['a']['span'] = 1;
```

I don't think there's a CKEditor 5 editor provider for DNN at the moment.

**Comment by muddeatr** [comment] 2019-10-25 21:32
OK, Thanks. I'll dig into this Monday then. Thanks again

________________________________

**Comment by Timo-Breumelhof** [comment] 2019-10-26 09:16
I just tried the suggestion by @w8tcha & @OllyHodgson , but I did not manage to select a custom JS file.
Uploaded it, synced file system but I cannot select it (does not appear in he drop-down).
Anybody else managed to do this?

**Comment by w8tcha** [comment] 2019-10-26 09:55
By default js files are not allowed. In the site settings you need to add ja to the list of allowed file extensions.

**Comment by ghost** [comment] 2019-10-26 18:58
Utilizing a shtml like document with script tags would be uneffected yes? I'll also say that I'v never seen anyone actually enforce restriction besides extension. Could probably just lie and call it .css or something if you really needed. How do these things translate to DNN?

**Comment by Timo-Breumelhof** [comment] 2019-10-27 12:56
> 
> 
> By default js files are not allowed. In the site settings you need to add ja to the list of allowed file extensions.

Hmmm, right I had thought about that being the limitation here.
I'll try again.

**Comment by Timo-Breumelhof** [comment] 2019-10-27 12:58
> 
> 
> Utilizing a shtml like document with script tags would be uneffected yes? I'll also say that I'v never seen anyone actually enforce restriction besides extension. Could probably just lie and call it .css or something if you really needed. How do these things translate to DNN?

Actually, not allowing JS is a security limitation of DNN.
The settings page uses DNNs way of getting a list of files and by default DNN does not show (or allow upload of) js files.

**Comment by w8tcha** [comment] 2019-10-27 14:21
Well the alternative would be to add the code to the editorOverride.js file in the folder "Providers\HtmlEditorProviders\DNNConnect.CKE\js"

**Comment by Timo-Breumelhof** [comment] 2019-10-27 18:42
Ok, I tried both options but the editor keeps changing.

```
<a><div>x</div></a> to
<div><a>x</a></div>
```

I added this to both files and in the console I do see that div = 1, but it has no effect.

		// Simply redefine DTD like this:
		CKEDITOR.dtd['a']['div'] = 1;
		CKEDITOR.dtd['a']['p'] = 1;
		CKEDITOR.dtd['a']['i'] = 1;
		CKEDITOR.dtd['a']['span'] = 1;
		
		console.log(CKEDITOR.dtd[ 'a' ]);

**Comment by valadas** [comment] 2019-10-28 16:57
Could it need a "Clear Cache" or a hard-reload after the changes?

**Comment by w8tcha** [comment] 2019-10-28 17:02
Yes you need to clear the cache or reload the page via ctrl+f5 at least in my tests it works as it should be.

**Comment by Timo-Breumelhof** [comment] 2019-10-28 17:20
@w8tcha Ok thanks. 
Hmm, I did that, I'll try again.

**Comment by Timo-Breumelhof** [comment] 2019-10-29 17:53
@w8tcha Ingo, I tried again, cleared the cache, but the editor keeps changing the HTML.
I added a custom.js file, that has this content:

CKEDITOR.dtd['a']['div'] = 1;
CKEDITOR.dtd['a']['p'] = 1;
CKEDITOR.dtd['a']['i'] = 1;
CKEDITOR.dtd['a']['span'] = 1;
console.log (CKEDITOR.dtd);

In the console I see:

![image](https://user-images.githubusercontent.com/8999382/67794839-a0f86480-fa7d-11e9-833a-9af6281d99c0.png)

Which seems correct & the JS runs
But if I enter this in source view:

`<a href="test"><div>test</div></a>`

It's still transformed to:

`<div><a href="test">test</a></div>`

when I swtich back and forth to WYSIWYG
Any pointers? Am I doing something wrong?
Thanks, Timo

**Comment by ghost** [comment] 2019-10-31 22:24
Man with this much trouble it might be worth just making your `<a></a>` the size of the container with css.

**Comment by w8tcha** [comment] 2019-11-03 00:24
@Timo which browser are you using? At least in chrome it works as expected

**Comment by muddeatr** [comment] 2019-11-03 00:45
Then I have a stupid question. Why doesn't it work with all other browsers other than SPY Crap Chrome? I've used Edge, IE, and Firefox but none of them work. Don't use Chrome never will. I've closed many accounts from finance companies to fitness software to anybody that tells me that they recommend Chrome 👎

**Comment by w8tcha** [comment] 2019-11-03 01:06
Well it also works in edge (which is also based on chrome)

**Comment by muddeatr** [comment] 2019-11-03 01:10
Then I guess I have to re-visit that because I was having the same issue with edge about six months ago. Thanks

**Comment by w8tcha** [comment] 2019-11-03 01:17
But i guess you didnt apply the fix i posted above six month ago

**Comment by muddeatr** [comment] 2019-11-03 01:29
That I can't say for sure so it is worth re-visiting. The past 6 months have been hell where I work. We were hit with ransomware that took out our whole network of 30 shipping terminals throughout the northeast.

**Comment by Timo-Breumelhof** [comment] 2019-11-04 18:30
@w8tcha FF, I'll have a try in Chrome.

**Comment by Timo-Breumelhof** [comment] 2019-11-05 16:29
Same in chrome, I must be doing something differently..

**Comment by w8tcha** [comment] 2019-11-05 19:35
I don't know. I use a fresh installed dnn and the default editor config. No modifications.

**Comment by muddeatr** [comment] 2019-11-05 19:43
@w8tcha so you don't use your own CKEditor? You use the default one that comes packaged in DNN?

**Comment by Timo-Breumelhof** [comment] 2019-11-05 19:47
Ok, I'll try a fresh install, this test install started off as DNN 9.1.1

**Comment by tmaler** [comment] 2020-04-09 16:05
I found an issue with the CKEditor removing empty tags. For example, we could not display font icons using i or span tags. In the ckeditor.js file, someone added a setting to remove these tags arrr. it's under $**removeEmpty**:  ...i:1,span:1.... I also removed i & span from **removeFormatTags**

**Comment by Timo-Breumelhof** [comment] 2020-04-14 08:27
@tmaler  Do you mean that this implementation of the editor overrules the CkEditor defaults?

**Comment by valadas** [comment] 2020-09-18 21:53
We are moving this project to the main Dnn repository, I am closing this issue and discussion can continue on https://github.com/dnnsoftware/Dnn.Platform/issues/4102

**Closed as completed by valadas** 2020-09-18 21:53 UTC
