### ISSUE TITLE
Editor config uses site theme layout, not the empty or popup layout

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNN-Connect/CKEditorProvider#130] opened 2019-11-05 17:15 UTC
In DNN 9.4.1 the CkEditor config "pop-up" uses the site layout, which includes the menu, logo footer etc.
This is wasting precious space.
I noticed this using my own theme and Xcillion.

Reproduce (two ways same result)
A:
- Open a page with the HTML editor (as host).
- Click the "Custom Editor Options" link.
Or B:
- PB > Site Settings > Site Behavior > More
- Click "Open HTML Editor manager"

Both ways the Editor config screen open wrapped in the "default skin":

![image](https://user-images.githubusercontent.com/8999382/68229946-7025ab80-fff8-11e9-9b49-0dc548107179.png)

**Comment by valadas** [comment] 2019-11-08 03:03
I cannot reproduce, can you think of anything else that is not vanilla install. SSL, SSL Offloading, disabled popups, etc?

**Comment by Timo-Breumelhof** [comment] 2019-11-08 23:24
Yes, I disabled pop-ups (I always do).
I'll see if it's not there when I switch them back on.

**Comment by Timo-Breumelhof** [comment] 2020-01-30 14:39
@valadas Ok, as soon as you switch pop-ups on for the site, the correct skin is loaded.

**Comment by valadas** [comment] 2020-02-06 07:00
Yeah, so I believe what happens here is that when popups are enabled, it load the popup.ascx template instead of the default one. When you disable them it uses the default one. I think one solution here is when loading a page like this in the context of the persona bar we should enforce the use of popup.ascx regardless of the config. I believe there is a querystring parameter to force displaying a specific one...

**Comment by valadas** [comment] 2020-02-06 07:05
Ok, since this would need to be handled on the main repository, I will close this issue in favor of https://github.com/dnnsoftware/Dnn.Platform/issues/3065

**Closed as completed by valadas** 2020-02-06 07:05 UTC
Labels: bug
