### ISSUE TITLE
No source syntax highlighting

### ISSUE THREAD

**Issue by roman-yagodin** [DNN-Connect/CKEditorProvider#77] opened 2016-11-29 10:38 UTC
HTML module content from Default website template (clean DNN 8.0.4 install):

![ckeditor-no-syntax-02](https://cloud.githubusercontent.com/assets/5691178/20706413/a843d3c0-b640-11e6-8b04-f006997a9834.png)

HTML Editor Manager - no CodeMirror themes?

![ckeditor-no-syntax-01](https://cloud.githubusercontent.com/assets/5691178/20706412/a84015a0-b640-11e6-8441-f69ffc57360b.png)

**Comment by ohine** [comment] 2016-12-28 18:45
The syntax highlighter was causing quite a few issues with generating invalid html. That's the reason it was removed from the DNN-Connect build. We spent quite a bit of time trying to track down the cause and had to just remove codemirror completely. It would be great if we could get the editor to load the version of codemirror that ships with the platform instead of duplicating and forking the project for just the editor.

**Comment by valadas** [comment] 2020-09-18 19:52
I am closing this issue, since it appears that was intetional to avoid other issues. If anyone is interested in developing such a feature, please open a new issue in the Platfrom repository, we are moving this project there with https://github.com/dnnsoftware/Dnn.Platform/pull/4096

**Closed as completed by valadas** 2020-09-18 19:52 UTC
