### ISSUE TITLE
Font color selection

### ISSUE THREAD

**Issue by ohine** [DNN-Connect/CKEditorProvider#10] opened 2015-09-21 15:11 UTC
When changing the font color of selected text, an extra closing tag is added and the color is applied incorrectly.

**Comment by valadas** [comment] 2020-09-18 18:29
I cannot reproduce in Dnn 9.7.1, I get this:
```
<p>Lorem <span style="color:#00923E">Ipsum</span></p>
```

If this is still relevant, please open a new issue with more details on how to reproduce, we are moving this project there with https://github.com/dnnsoftware/Dnn.Platform/pull/4096

**Closed as completed by valadas** 2020-09-18 18:29 UTC
